// Auto-generated by resnet_simple_to_linalg.py (torch-mlir). emit=linalg-tensors. Tensor sizes aligned with RVV_code_gen_via_MLIR_xDSL/tests/riscv_tests/resnet_simple_memref.mlir (1x3x5x5 in, 11x11 pad canvas, 9x9 conv, pool 9x9/81, FC 4).
#map = affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>
#map1 = affine_map<(d0, d1, d2, d3) -> (d1)>
#map2 = affine_map<(d0, d1) -> (d0, d1)>
#map3 = affine_map<(d0, d1) -> (d1)>
module attributes {torch.debug_module_name = "ResNetSimple"} {
  func.func @forward(%arg0: tensor<1x3x5x5xf32>) -> tensor<1x4xf32> {
    %cst = arith.constant dense<[-0.0106039243, 0.0288954284, -0.0788141414, 0.11419557]> : tensor<4xf32>
    %cst_0 = arith.constant 0.000000e+00 : f32
    %cst_1 = arith.constant 1.000000e-05 : f64
    %cst_2 = arith.constant 8.100000e+01 : f32
    %cst_3 = arith.constant dense_resource<__elided__> : tensor<4x3x3x3xf32>
    %cst_4 = arith.constant dense<1.000000e+00> : tensor<4xf32>
    %cst_5 = arith.constant dense<0.000000e+00> : tensor<4xf32>
    %cst_6 = arith.constant dense<[-0.174916685, -0.409810841, -0.106357574, 0.106878221]> : tensor<4xf32>
    %cst_7 = arith.constant dense_resource<__elided__> : tensor<4x4xf32>
    %padded = tensor.pad %arg0 low[0, 0, 3, 3] high[0, 0, 3, 3] {
    ^bb0(%arg1: index, %arg2: index, %arg3: index, %arg4: index):
      tensor.yield %cst_0 : f32
    } : tensor<1x3x5x5xf32> to tensor<1x3x11x11xf32>
    %0 = tensor.empty() : tensor<1x4x9x9xf32>
    %broadcasted = linalg.broadcast ins(%cst : tensor<4xf32>) outs(%0 : tensor<1x4x9x9xf32>) dimensions = [0, 2, 3] 
    %1 = linalg.conv_2d_nchw_fchw {dilations = dense<1> : vector<2xi64>, strides = dense<1> : vector<2xi64>} ins(%padded, %cst_3 : tensor<1x3x11x11xf32>, tensor<4x3x3x3xf32>) outs(%broadcasted : tensor<1x4x9x9xf32>) -> tensor<1x4x9x9xf32>
    %2 = linalg.generic {indexing_maps = [#map, #map1, #map1, #map1, #map1, #map], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} ins(%1, %cst_4, %cst_5, %cst_5, %cst_4 : tensor<1x4x9x9xf32>, tensor<4xf32>, tensor<4xf32>, tensor<4xf32>, tensor<4xf32>) outs(%1 : tensor<1x4x9x9xf32>) {
    ^bb0(%in: f32, %in_8: f32, %in_9: f32, %in_10: f32, %in_11: f32, %out: f32):
      %13 = arith.truncf %cst_1 : f64 to f32
      %14 = arith.addf %in_11, %13 : f32
      %15 = math.rsqrt %14 : f32
      %16 = arith.subf %in, %in_10 : f32
      %17 = arith.mulf %16, %15 : f32
      %18 = arith.mulf %17, %in_8 : f32
      %19 = arith.addf %18, %in_9 : f32
      linalg.yield %19 : f32
    } -> tensor<1x4x9x9xf32>
    %3 = linalg.generic {indexing_maps = [#map, #map], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} ins(%2 : tensor<1x4x9x9xf32>) outs(%0 : tensor<1x4x9x9xf32>) {
    ^bb0(%in: f32, %out: f32):
      %13 = arith.cmpf ugt, %in, %cst_0 : f32
      %14 = arith.select %13, %in, %cst_0 : f32
      linalg.yield %14 : f32
    } -> tensor<1x4x9x9xf32>
    %4 = tensor.empty() : tensor<1x4x1x1xf32>
    %5 = linalg.fill ins(%cst_0 : f32) outs(%4 : tensor<1x4x1x1xf32>) -> tensor<1x4x1x1xf32>
    %6 = tensor.empty() : tensor<9x9xf32>
    %7 = linalg.pooling_nchw_sum {dilations = dense<1> : vector<2xi64>, strides = dense<9> : vector<2xi64>} ins(%3, %6 : tensor<1x4x9x9xf32>, tensor<9x9xf32>) outs(%5 : tensor<1x4x1x1xf32>) -> tensor<1x4x1x1xf32>
    %8 = linalg.generic {indexing_maps = [#map, #map], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} ins(%7 : tensor<1x4x1x1xf32>) outs(%4 : tensor<1x4x1x1xf32>) {
    ^bb0(%in: f32, %out: f32):
      %13 = arith.divf %in, %cst_2 : f32
      linalg.yield %13 : f32
    } -> tensor<1x4x1x1xf32>
    %collapsed = tensor.collapse_shape %8 [[0], [1, 2, 3]] : tensor<1x4x1x1xf32> into tensor<1x4xf32>
    %9 = tensor.empty() : tensor<1x4xf32>
    %10 = linalg.fill ins(%cst_0 : f32) outs(%9 : tensor<1x4xf32>) -> tensor<1x4xf32>
    %11 = linalg.matmul ins(%collapsed, %cst_7 : tensor<1x4xf32>, tensor<4x4xf32>) outs(%10 : tensor<1x4xf32>) -> tensor<1x4xf32>
    %12 = linalg.generic {indexing_maps = [#map2, #map3, #map2], iterator_types = ["parallel", "parallel"]} ins(%11, %cst_6 : tensor<1x4xf32>, tensor<4xf32>) outs(%9 : tensor<1x4xf32>) {
    ^bb0(%in: f32, %in_8: f32, %out: f32):
      %13 = arith.addf %in, %in_8 : f32
      linalg.yield %13 : f32
    } -> tensor<1x4xf32>
    return %12 : tensor<1x4xf32>
  }
}
